# Generated by Django 4.2.6 on 2023-11-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('featured_as', models.CharField(max_length=255)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('runtime', models.CharField(default='120 min', max_length=10)),
                ('genre', models.CharField(default='Default Genre', max_length=255)),
                ('rating', models.FloatField()),
                ('show_timings', models.JSONField(default=list)),
                ('description', models.TextField()),
            ],
        ),
    ]
