# Generated by Django 4.2.6 on 2023-11-26 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_show_timings_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
