# Generated by Django 4.2.6 on 2023-11-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater', '0004_theater_shows'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_timing', models.DateTimeField()),
                ('seat_matrix', models.JSONField(default=list)),
                ('no_of_rows', models.IntegerField()),
                ('no_of_cols', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theater')),
            ],
        ),
    ]
