# Generated by Django 4.2.6 on 2023-11-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
