# Generated by Django 4.2.6 on 2023-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_show_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
