# Generated by Django 4.2.6 on 2023-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_show_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='discounted_price',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
