# Generated by Django 4.2.6 on 2023-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ticket_created_at_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reward_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed'),
        ),
    ]
