# Generated by Django 4.2.6 on 2023-11-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='theatre',
            new_name='theater',
        ),
    ]
