# Generated by Django 4.2.6 on 2023-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_rename_theatre_screen_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='cuisines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='theater',
            name='seatingCategories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='theater',
            name='technologies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='theater',
            name='zip_code',
            field=models.CharField(default='95110', max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
