# Generated by Django 4.2.6 on 2023-11-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_theater_cuisines_theater_seatingcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='shows',
            field=models.JSONField(default=list),
        ),
    ]
