# Generated by Django 4.2.6 on 2023-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_theater_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='no_of_cols',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theater',
            name='no_of_rows',
            field=models.IntegerField(default=0),
        ),
    ]
