# Generated by Django 4.2.6 on 2023-11-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_theater_no_of_cols_theater_no_of_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='address',
            field=models.CharField(default=''),
        ),
    ]
