# Generated by Django 4.2.6 on 2023-11-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_theater_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='seatingCategories',
        ),
    ]
