# Generated by Django 4.2.6 on 2023-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_remove_theater_seatingcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='short_address',
            field=models.CharField(default=''),
        ),
    ]
